title: Dan Gish
theme: minima             # default GitHub Pages theme
description: "Humans are cool."
url: "https://djgish485.github.io"
author: "Dan Gish"
google_site_verification: Cy8rP5ylvS0PzScuvusUjvnO8p8y01NVDR_lOK2C3KY

twitter:
  username: djgish          # <-- your @ handle, no “@”

logo: /assets/img/social-card.jpg   # tiny fallback
image: /assets/img/social-card.jpg  # default OG/Twitter card

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap   
  - jekyll-redirect-from


defaults:                     # make sure every page has an image
  - scope:
      path: ""
    values:
      image: /assets/img/social-card.jpg
